platform :ios, '12.0'

source 'https://cdn.cocoapods.org/'
source 'https://github.com/SumSubstance/Specs.git'

# Add these permissions to Info.plist after pod install
# NSCameraUsageDescription
# NSMicrophoneUsageDescription
# NSPhotoLibraryUsageDescription
# NSLocationWhenInUseUsageDescription 